repository:
  delete_branch_on_merge: false

branches:
  - name: master   
    protection:
      required_pull_request_reviews:        
        required_approving_review_count: 1               
      required_status_checks:        
        strict: true        
        contexts: []     
      enforce_admins: true
