repository:
  delete_branch_on_merge: true



branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
        dismissal_restrictions: {}
      required_status_checks:
        strict: true
        contexts: ['YAML lint']
      enforce_admins: null
      restrictions: null
